/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OwnerOnboardingRouteImport } from './routes/owner-onboarding'
import { Route as OpenGamesRouteImport } from './routes/open-games'
import { Route as LiveScoresRouteImport } from './routes/live-scores'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurfsSlugRouteImport } from './routes/turfs.$slug'
import { Route as TournamentsIdRouteImport } from './routes/tournaments_.$id'
import { Route as SquadIdRouteImport } from './routes/squad.$id'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSquadFillRouteImport } from './routes/_authenticated/squad-fill'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedOwnerRouteRouteImport } from './routes/_authenticated/owner/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedVerifyIdRouteImport } from './routes/_authenticated/verify.$id'
import { Route as AuthenticatedSquadFillNewRouteImport } from './routes/_authenticated/squad-fill.new'
import { Route as AuthenticatedOwnerTournamentsRouteImport } from './routes/_authenticated/owner/tournaments'
import { Route as AuthenticatedOwnerLiveRouteImport } from './routes/_authenticated/owner/live'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated/owner/dashboard'
import { Route as AuthenticatedOwnerCalendarRouteImport } from './routes/_authenticated/owner/calendar'
import { Route as AuthenticatedOwnerBookingsRouteImport } from './routes/_authenticated/owner/bookings'
import { Route as AuthenticatedOwnerAnalyticsRouteImport } from './routes/_authenticated/owner/analytics'
import { Route as AuthenticatedCheckoutTurfIdRouteImport } from './routes/_authenticated/checkout.$turfId'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTurfsRouteImport } from './routes/_authenticated/admin/turfs'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin/tournaments'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedOwnerTurfsIdRouteImport } from './routes/_authenticated/owner/turfs.$id'
import { Route as AuthenticatedOwnerTournamentsIdRouteImport } from './routes/_authenticated/owner/tournaments.$id'
import { Route as AuthenticatedOwnerBookingsNewRouteImport } from './routes/_authenticated/owner/bookings.new'
import { Route as AuthenticatedBookingsIdConfirmationRouteImport } from './routes/_authenticated/bookings_.$id.confirmation'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOnboardingRoute = OwnerOnboardingRouteImport.update({
  id: '/owner-onboarding',
  path: '/owner-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenGamesRoute = OpenGamesRouteImport.update({
  id: '/open-games',
  path: '/open-games',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveScoresRoute = LiveScoresRouteImport.update({
  id: '/live-scores',
  path: '/live-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurfsSlugRoute = TurfsSlugRouteImport.update({
  id: '/turfs/$slug',
  path: '/turfs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments_/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadIdRoute = SquadIdRouteImport.update({
  id: '/squad/$id',
  path: '/squad/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadFillRoute = AuthenticatedSquadFillRouteImport.update({
  id: '/squad-fill',
  path: '/squad-fill',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRouteRoute = AuthenticatedOwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedVerifyIdRoute = AuthenticatedVerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadFillNewRoute =
  AuthenticatedSquadFillNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSquadFillRoute,
  } as any)
const AuthenticatedOwnerTournamentsRoute =
  AuthenticatedOwnerTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedOwnerLiveRoute = AuthenticatedOwnerLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedOwnerRouteRoute,
} as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedOwnerCalendarRoute =
  AuthenticatedOwnerCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedOwnerBookingsRoute =
  AuthenticatedOwnerBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedOwnerAnalyticsRoute =
  AuthenticatedOwnerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedCheckoutTurfIdRoute =
  AuthenticatedCheckoutTurfIdRouteImport.update({
    id: '/checkout/$turfId',
    path: '/checkout/$turfId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBookingsRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTurfsRoute = AuthenticatedAdminTurfsRouteImport.update({
  id: '/turfs',
  path: '/turfs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedOwnerTurfsIdRoute =
  AuthenticatedOwnerTurfsIdRouteImport.update({
    id: '/turfs/$id',
    path: '/turfs/$id',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedOwnerTournamentsIdRoute =
  AuthenticatedOwnerTournamentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOwnerTournamentsRoute,
  } as any)
const AuthenticatedOwnerBookingsNewRoute =
  AuthenticatedOwnerBookingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOwnerBookingsRoute,
  } as any)
const AuthenticatedBookingsIdConfirmationRoute =
  AuthenticatedBookingsIdConfirmationRouteImport.update({
    id: '/bookings_/$id/confirmation',
    path: '/bookings/$id/confirmation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-scores': typeof LiveScoresRoute
  '/open-games': typeof OpenGamesRoute
  '/owner-onboarding': typeof OwnerOnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tournaments': typeof TournamentsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/squad-fill': typeof AuthenticatedSquadFillRouteWithChildren
  '/teams': typeof AuthenticatedTeamsRoute
  '/squad/$id': typeof SquadIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/turfs/$slug': typeof TurfsSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/turfs': typeof AuthenticatedAdminTurfsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/checkout/$turfId': typeof AuthenticatedCheckoutTurfIdRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRouteWithChildren
  '/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/live': typeof AuthenticatedOwnerLiveRoute
  '/owner/tournaments': typeof AuthenticatedOwnerTournamentsRouteWithChildren
  '/squad-fill/new': typeof AuthenticatedSquadFillNewRoute
  '/verify/$id': typeof AuthenticatedVerifyIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/bookings/$id/confirmation': typeof AuthenticatedBookingsIdConfirmationRoute
  '/owner/bookings/new': typeof AuthenticatedOwnerBookingsNewRoute
  '/owner/tournaments/$id': typeof AuthenticatedOwnerTournamentsIdRoute
  '/owner/turfs/$id': typeof AuthenticatedOwnerTurfsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-scores': typeof LiveScoresRoute
  '/open-games': typeof OpenGamesRoute
  '/owner-onboarding': typeof OwnerOnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tournaments': typeof TournamentsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/squad-fill': typeof AuthenticatedSquadFillRouteWithChildren
  '/teams': typeof AuthenticatedTeamsRoute
  '/squad/$id': typeof SquadIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/turfs/$slug': typeof TurfsSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/turfs': typeof AuthenticatedAdminTurfsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/checkout/$turfId': typeof AuthenticatedCheckoutTurfIdRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRouteWithChildren
  '/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/live': typeof AuthenticatedOwnerLiveRoute
  '/owner/tournaments': typeof AuthenticatedOwnerTournamentsRouteWithChildren
  '/squad-fill/new': typeof AuthenticatedSquadFillNewRoute
  '/verify/$id': typeof AuthenticatedVerifyIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/bookings/$id/confirmation': typeof AuthenticatedBookingsIdConfirmationRoute
  '/owner/bookings/new': typeof AuthenticatedOwnerBookingsNewRoute
  '/owner/tournaments/$id': typeof AuthenticatedOwnerTournamentsIdRoute
  '/owner/turfs/$id': typeof AuthenticatedOwnerTurfsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-scores': typeof LiveScoresRoute
  '/open-games': typeof OpenGamesRoute
  '/owner-onboarding': typeof OwnerOnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tournaments': typeof TournamentsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/squad-fill': typeof AuthenticatedSquadFillRouteWithChildren
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/squad/$id': typeof SquadIdRoute
  '/tournaments_/$id': typeof TournamentsIdRoute
  '/turfs/$slug': typeof TurfsSlugRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/_authenticated/admin/turfs': typeof AuthenticatedAdminTurfsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/checkout/$turfId': typeof AuthenticatedCheckoutTurfIdRoute
  '/_authenticated/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/_authenticated/owner/bookings': typeof AuthenticatedOwnerBookingsRouteWithChildren
  '/_authenticated/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/_authenticated/owner/live': typeof AuthenticatedOwnerLiveRoute
  '/_authenticated/owner/tournaments': typeof AuthenticatedOwnerTournamentsRouteWithChildren
  '/_authenticated/squad-fill/new': typeof AuthenticatedSquadFillNewRoute
  '/_authenticated/verify/$id': typeof AuthenticatedVerifyIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/bookings_/$id/confirmation': typeof AuthenticatedBookingsIdConfirmationRoute
  '/_authenticated/owner/bookings/new': typeof AuthenticatedOwnerBookingsNewRoute
  '/_authenticated/owner/tournaments/$id': typeof AuthenticatedOwnerTournamentsIdRoute
  '/_authenticated/owner/turfs/$id': typeof AuthenticatedOwnerTurfsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/forgot-password'
    | '/live-scores'
    | '/open-games'
    | '/owner-onboarding'
    | '/sitemap.xml'
    | '/tournaments'
    | '/unauthorized'
    | '/admin'
    | '/owner'
    | '/bookings'
    | '/dashboard'
    | '/favorites'
    | '/notifications'
    | '/profile'
    | '/squad-fill'
    | '/teams'
    | '/squad/$id'
    | '/tournaments/$id'
    | '/turfs/$slug'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/tickets'
    | '/admin/tournaments'
    | '/admin/turfs'
    | '/admin/users'
    | '/bookings/$id'
    | '/checkout/$turfId'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/calendar'
    | '/owner/dashboard'
    | '/owner/live'
    | '/owner/tournaments'
    | '/squad-fill/new'
    | '/verify/$id'
    | '/admin/'
    | '/owner/'
    | '/bookings/$id/confirmation'
    | '/owner/bookings/new'
    | '/owner/tournaments/$id'
    | '/owner/turfs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/forgot-password'
    | '/live-scores'
    | '/open-games'
    | '/owner-onboarding'
    | '/sitemap.xml'
    | '/tournaments'
    | '/unauthorized'
    | '/bookings'
    | '/dashboard'
    | '/favorites'
    | '/notifications'
    | '/profile'
    | '/squad-fill'
    | '/teams'
    | '/squad/$id'
    | '/tournaments/$id'
    | '/turfs/$slug'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/tickets'
    | '/admin/tournaments'
    | '/admin/turfs'
    | '/admin/users'
    | '/bookings/$id'
    | '/checkout/$turfId'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/calendar'
    | '/owner/dashboard'
    | '/owner/live'
    | '/owner/tournaments'
    | '/squad-fill/new'
    | '/verify/$id'
    | '/admin'
    | '/owner'
    | '/bookings/$id/confirmation'
    | '/owner/bookings/new'
    | '/owner/tournaments/$id'
    | '/owner/turfs/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/forgot-password'
    | '/live-scores'
    | '/open-games'
    | '/owner-onboarding'
    | '/sitemap.xml'
    | '/tournaments'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/owner'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/squad-fill'
    | '/_authenticated/teams'
    | '/squad/$id'
    | '/tournaments_/$id'
    | '/turfs/$slug'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/admin/turfs'
    | '/_authenticated/admin/users'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/checkout/$turfId'
    | '/_authenticated/owner/analytics'
    | '/_authenticated/owner/bookings'
    | '/_authenticated/owner/calendar'
    | '/_authenticated/owner/dashboard'
    | '/_authenticated/owner/live'
    | '/_authenticated/owner/tournaments'
    | '/_authenticated/squad-fill/new'
    | '/_authenticated/verify/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/owner/'
    | '/_authenticated/bookings_/$id/confirmation'
    | '/_authenticated/owner/bookings/new'
    | '/_authenticated/owner/tournaments/$id'
    | '/_authenticated/owner/turfs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveScoresRoute: typeof LiveScoresRoute
  OpenGamesRoute: typeof OpenGamesRoute
  OwnerOnboardingRoute: typeof OwnerOnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TournamentsRoute: typeof TournamentsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  SquadIdRoute: typeof SquadIdRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  TurfsSlugRoute: typeof TurfsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-onboarding': {
      id: '/owner-onboarding'
      path: '/owner-onboarding'
      fullPath: '/owner-onboarding'
      preLoaderRoute: typeof OwnerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-games': {
      id: '/open-games'
      path: '/open-games'
      fullPath: '/open-games'
      preLoaderRoute: typeof OpenGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-scores': {
      id: '/live-scores'
      path: '/live-scores'
      fullPath: '/live-scores'
      preLoaderRoute: typeof LiveScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turfs/$slug': {
      id: '/turfs/$slug'
      path: '/turfs/$slug'
      fullPath: '/turfs/$slug'
      preLoaderRoute: typeof TurfsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments_/$id': {
      id: '/tournaments_/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad/$id': {
      id: '/squad/$id'
      path: '/squad/$id'
      fullPath: '/squad/$id'
      preLoaderRoute: typeof SquadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad-fill': {
      id: '/_authenticated/squad-fill'
      path: '/squad-fill'
      fullPath: '/squad-fill'
      preLoaderRoute: typeof AuthenticatedSquadFillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/verify/$id': {
      id: '/_authenticated/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof AuthenticatedVerifyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad-fill/new': {
      id: '/_authenticated/squad-fill/new'
      path: '/new'
      fullPath: '/squad-fill/new'
      preLoaderRoute: typeof AuthenticatedSquadFillNewRouteImport
      parentRoute: typeof AuthenticatedSquadFillRoute
    }
    '/_authenticated/owner/tournaments': {
      id: '/_authenticated/owner/tournaments'
      path: '/tournaments'
      fullPath: '/owner/tournaments'
      preLoaderRoute: typeof AuthenticatedOwnerTournamentsRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/live': {
      id: '/_authenticated/owner/live'
      path: '/live'
      fullPath: '/owner/live'
      preLoaderRoute: typeof AuthenticatedOwnerLiveRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/calendar': {
      id: '/_authenticated/owner/calendar'
      path: '/calendar'
      fullPath: '/owner/calendar'
      preLoaderRoute: typeof AuthenticatedOwnerCalendarRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/bookings': {
      id: '/_authenticated/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof AuthenticatedOwnerBookingsRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/analytics': {
      id: '/_authenticated/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof AuthenticatedOwnerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/checkout/$turfId': {
      id: '/_authenticated/checkout/$turfId'
      path: '/checkout/$turfId'
      fullPath: '/checkout/$turfId'
      preLoaderRoute: typeof AuthenticatedCheckoutTurfIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/turfs': {
      id: '/_authenticated/admin/turfs'
      path: '/turfs'
      fullPath: '/admin/turfs'
      preLoaderRoute: typeof AuthenticatedAdminTurfsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/owner/turfs/$id': {
      id: '/_authenticated/owner/turfs/$id'
      path: '/turfs/$id'
      fullPath: '/owner/turfs/$id'
      preLoaderRoute: typeof AuthenticatedOwnerTurfsIdRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/tournaments/$id': {
      id: '/_authenticated/owner/tournaments/$id'
      path: '/$id'
      fullPath: '/owner/tournaments/$id'
      preLoaderRoute: typeof AuthenticatedOwnerTournamentsIdRouteImport
      parentRoute: typeof AuthenticatedOwnerTournamentsRoute
    }
    '/_authenticated/owner/bookings/new': {
      id: '/_authenticated/owner/bookings/new'
      path: '/new'
      fullPath: '/owner/bookings/new'
      preLoaderRoute: typeof AuthenticatedOwnerBookingsNewRouteImport
      parentRoute: typeof AuthenticatedOwnerBookingsRoute
    }
    '/_authenticated/bookings_/$id/confirmation': {
      id: '/_authenticated/bookings_/$id/confirmation'
      path: '/bookings/$id/confirmation'
      fullPath: '/bookings/$id/confirmation'
      preLoaderRoute: typeof AuthenticatedBookingsIdConfirmationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRoute
  AuthenticatedAdminTurfsRoute: typeof AuthenticatedAdminTurfsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminTournamentsRoute: AuthenticatedAdminTournamentsRoute,
    AuthenticatedAdminTurfsRoute: AuthenticatedAdminTurfsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedOwnerBookingsRouteChildren {
  AuthenticatedOwnerBookingsNewRoute: typeof AuthenticatedOwnerBookingsNewRoute
}

const AuthenticatedOwnerBookingsRouteChildren: AuthenticatedOwnerBookingsRouteChildren =
  {
    AuthenticatedOwnerBookingsNewRoute: AuthenticatedOwnerBookingsNewRoute,
  }

const AuthenticatedOwnerBookingsRouteWithChildren =
  AuthenticatedOwnerBookingsRoute._addFileChildren(
    AuthenticatedOwnerBookingsRouteChildren,
  )

interface AuthenticatedOwnerTournamentsRouteChildren {
  AuthenticatedOwnerTournamentsIdRoute: typeof AuthenticatedOwnerTournamentsIdRoute
}

const AuthenticatedOwnerTournamentsRouteChildren: AuthenticatedOwnerTournamentsRouteChildren =
  {
    AuthenticatedOwnerTournamentsIdRoute: AuthenticatedOwnerTournamentsIdRoute,
  }

const AuthenticatedOwnerTournamentsRouteWithChildren =
  AuthenticatedOwnerTournamentsRoute._addFileChildren(
    AuthenticatedOwnerTournamentsRouteChildren,
  )

interface AuthenticatedOwnerRouteRouteChildren {
  AuthenticatedOwnerAnalyticsRoute: typeof AuthenticatedOwnerAnalyticsRoute
  AuthenticatedOwnerBookingsRoute: typeof AuthenticatedOwnerBookingsRouteWithChildren
  AuthenticatedOwnerCalendarRoute: typeof AuthenticatedOwnerCalendarRoute
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
  AuthenticatedOwnerLiveRoute: typeof AuthenticatedOwnerLiveRoute
  AuthenticatedOwnerTournamentsRoute: typeof AuthenticatedOwnerTournamentsRouteWithChildren
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
  AuthenticatedOwnerTurfsIdRoute: typeof AuthenticatedOwnerTurfsIdRoute
}

const AuthenticatedOwnerRouteRouteChildren: AuthenticatedOwnerRouteRouteChildren =
  {
    AuthenticatedOwnerAnalyticsRoute: AuthenticatedOwnerAnalyticsRoute,
    AuthenticatedOwnerBookingsRoute:
      AuthenticatedOwnerBookingsRouteWithChildren,
    AuthenticatedOwnerCalendarRoute: AuthenticatedOwnerCalendarRoute,
    AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
    AuthenticatedOwnerLiveRoute: AuthenticatedOwnerLiveRoute,
    AuthenticatedOwnerTournamentsRoute:
      AuthenticatedOwnerTournamentsRouteWithChildren,
    AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
    AuthenticatedOwnerTurfsIdRoute: AuthenticatedOwnerTurfsIdRoute,
  }

const AuthenticatedOwnerRouteRouteWithChildren =
  AuthenticatedOwnerRouteRoute._addFileChildren(
    AuthenticatedOwnerRouteRouteChildren,
  )

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedSquadFillRouteChildren {
  AuthenticatedSquadFillNewRoute: typeof AuthenticatedSquadFillNewRoute
}

const AuthenticatedSquadFillRouteChildren: AuthenticatedSquadFillRouteChildren =
  {
    AuthenticatedSquadFillNewRoute: AuthenticatedSquadFillNewRoute,
  }

const AuthenticatedSquadFillRouteWithChildren =
  AuthenticatedSquadFillRoute._addFileChildren(
    AuthenticatedSquadFillRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedOwnerRouteRoute: typeof AuthenticatedOwnerRouteRouteWithChildren
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSquadFillRoute: typeof AuthenticatedSquadFillRouteWithChildren
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedCheckoutTurfIdRoute: typeof AuthenticatedCheckoutTurfIdRoute
  AuthenticatedVerifyIdRoute: typeof AuthenticatedVerifyIdRoute
  AuthenticatedBookingsIdConfirmationRoute: typeof AuthenticatedBookingsIdConfirmationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedOwnerRouteRoute: AuthenticatedOwnerRouteRouteWithChildren,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSquadFillRoute: AuthenticatedSquadFillRouteWithChildren,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedCheckoutTurfIdRoute: AuthenticatedCheckoutTurfIdRoute,
  AuthenticatedVerifyIdRoute: AuthenticatedVerifyIdRoute,
  AuthenticatedBookingsIdConfirmationRoute:
    AuthenticatedBookingsIdConfirmationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveScoresRoute: LiveScoresRoute,
  OpenGamesRoute: OpenGamesRoute,
  OwnerOnboardingRoute: OwnerOnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TournamentsRoute: TournamentsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  SquadIdRoute: SquadIdRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  TurfsSlugRoute: TurfsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
